### ISSUE TITLE
Need help with settings.analyzer file

### ISSUE THREAD

**Issue by Ichy84** [Legedric/ptmagic#240]
Hello,

Please help me out, i got an error and dont know what i did wrong.

FATAL - Error loading configuration! System.FormatException Could not parse the JSON file. Error on line number '65': '"PairsProperties": { // Properties for PAIRS.PROPERTIES
"MARKET": USDT'.    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Globals.SystemConfiguration.LoadSettings(String basePath) in D:\Tools\PTMagic\Globals\SystemConfiguration.cs:line 36
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 52

Unhandled Exception: System.FormatException: Could not parse the JSON file. Error on line number '65': '"PairsProperties": { // Properties for PAIRS.PROPERTIES
"MARKET": USDT'. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: U. Path 'AnalyzerSettings.GlobalSettings[0].PairsProperties.MARKET', line 65, position 14.
   at Newtonsoft.Json.JsonTextReader.ParseValue()...
 

![image](https://user-images.githubusercontent.com/36775146/36804225-3522ecaa-1cba-11e8-8980-d2a6ff9014ff.png)

**Comment by Legedric** [comment]
Any string of characters has to be in quotes to be valid. So "USDT", "BTCUSDT", "EMAGAIN" etc.  
true and false however do not have to be in quotes as they are boolean values.

**Comment by Ichy84** [comment]
Thank you for the quick reply, but i still get an error...

2018/02/28 19:19:57.643 FATAL - Error loading configuration! System.FormatException Could not parse the JSON file. Error on line number '66': '"MARKET": "USDT"
"ALL_enabled_pairs" : "BTCUSDT"'.    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Globals.SystemConfiguration.LoadSettings(String basePath) in D:\Tools\PTMagic\Globals\SystemConfiguration.cs:line 36
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 52

Unhandled Exception: System.FormatException: Could not parse the JSON file. Error on line number '66': '"MARKET": "USDT"
"ALL_enabled_pairs" : "BTCUSDT"'. ---> Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: ". Path 'AnalyzerSettings.GlobalSettings[0].PairsProperties.MARKET', line 66, position 3.

**Comment by Othon3** [comment]
There is no comma after true (on line 67)

**Comment by Ichy84** [comment]
the comas, yes.
Thank you, danke schön
