### ISSUE TITLE
PTM won't start

### ISSUE THREAD

**Issue by Fransenson** [Legedric/ptmagic#304]
After updating to 1.3.0 and restarting PTM it won't start. Error Logs as follows:

```
17|PTMagic | 2018-03-12 14:57 +01:00: Unhandled Exception:2018-03-12 14:57 +01:00:  2018-03-12 14:57 +01:00: System.NullReferenceException: Object reference not set to an instance of an object.
17|PTMagic |    at PTMagic.PTMagic.MarketTrendCheckTimer_Elapsed(Object sender, ElapsedEventArgs e) in D:\Tools\PTMagic\PTMagic\PTMagic.cs:line 526
17|PTMagic |    at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 150
17|PTMagic | 2018-03-12 15:01 +01:00: 
17|PTMagic | Unhandled Exception: 2018-03-12 15:01 +01:00: System.NullReferenceException: Object reference not set to an instance of an object.
17|PTMagic |    at PTMagic.PTMagic.MarketTrendCheckTimer_Elapsed(Object sender, ElapsedEventArgs e) in D:\Tools\PTMagic\PTMagic\PTMagic.cs:line 526
17|PTMagic |    at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 150

```

Can you point me to anything that I might have broken?

**Comment by Fransenson** [comment]
Nevermind, there was a comma too much in the single market settings after adding the CoinAge trigger.
