### ISSUE TITLE
Dotnet has stopped working. What did I miss?

### ISSUE THREAD

**Issue by Dysrupt** [Legedric/ptmagic#32]
C:\Users\Administrator\Desktop\PROFITTRAILERMAGIC\PTMagic.1.0.2\PTMagic 1.0.2\PT
Magic>dotnet Monitor/Monitor.dll

Unhandled Exception: System.FormatException: Could not parse the JSON file. Erro
r on line number '3': '"PTMagicBasePath": "C:\\Users\\Administrator\\Desktop\\PR
OFITTRAILERMAGIC\\PTMagic.1.0.2\\PTMagic 1.0.2\\"
"Logging": {'. ---> Newtonsoft.Json.JsonReaderException: After parsing a value a
n unexpected character was encountered: ". Path 'PTMagicBasePath', line 3, posit
ion 2.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSett
ings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadS
ettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings sett
ings)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(
Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Str
eam stream)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean
reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 provide
rs)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Monitor.Program.Main(String[] args) in D:\Tools\PTMagic\Monitor\Program.cs
:line 21

C:\Users\Administrator\Desktop\PROFITTRAILERMAGIC\PTMagic.1.0.2\PTMagic 1.0.2\PT
Magic>pause
Press any key to continue . . .

**Comment by sitespagando** [comment]
I'm wrong, I've tried everything I really want to use it, but I do not know how to solve this problem, I opened a topic too

**Comment by Legedric** [comment]
Please use double backslashes when you are using windows path names.  
So please change you settings for PTMagicBasePath to this:  
'"PTMagicBasePath": "C:\\Users\\Administrator\\Desktop\\PR
OFITTRAILERMAGIC\\PTMagic.1.0.2\\PTMagic 1.0.2\\"

**Comment by Dysrupt** [comment]
I did do that as well. Im going to start over
