### ISSUE TITLE
[Resolved!] There was a problem with the Binance Exchange.

### ISSUE THREAD

**Issue by nicekon** [Legedric/ptmagic#393]
<img width="1368" alt="2018-04-06 13 32 37" src="https://user-images.githubusercontent.com/792574/38403531-166224be-399f-11e8-86b1-09b077b7af41.png">
<img width="689" alt="2018-04-06 13 32 49" src="https://user-images.githubusercontent.com/792574/38403534-1a554740-399f-11e8-9eab-c22d3aaf3998.png">

```
0|PTMagic( | 2018/04/06 04:31:46.938 ERROR - Unable to contact Binance for fresh market data. Trying again in 1 minute(s). 

0|PTMagic( | 2018-04-06 04:32 +00:00: 2018/04/06 04:32:46.734 INFO -  
0|PTMagic( | 2018-04-06 04:32 +00:00: 2018/04/06 04:32:46.734 INFO - ########################################################## 
0|PTMagic( | 2018/04/06 04:32:46.734 INFO - #********************************************************# 
0|PTMagic( | 2018/04/06 04:32:46.734 INFO - Starting market trend check with Version 1.4.0 
0|PTMagic( | 2018-04-06 04:32 +00:00: 2018/04/06 04:32:46.736 INFO - CoinMarketCap - Getting market data... 
0|PTMagic( | 2018-04-06 04:32 +00:00: 2018/04/06 04:32:46.766 INFO - CoinMarketCap - Market data received for 100 currencies 
0|PTMagic( | 2018-04-06 04:32 +00:00: 2018/04/06 04:32:46.786 INFO - CoinMarketCap - Market data saved. 
0|PTMagic( | 2018-04-06 04:32 +00:00: 2018/04/06 04:32:46.796 INFO - CoinMarketCap - Market data cleaned. 
0|PTMagic( | 2018-04-06 04:32 +00:00: 2018/04/06 04:32:46.796 INFO - Binance - Getting market data... 
0|PTMagic( | 2018-04-06 04:32 +00:00: 2018/04/06 04:32:46.866 INFO - Binance - Getting main market price... 
0|PTMagic( | 2018-04-06 04:32 +00:00: 2018/04/06 04:32:46.989 FATAL - The remote server returned an error: (400) Bad Request. System.Net.WebException The remote server returned an error: (400) Bad Request.    at System.Net.HttpWebRequest.GetResponse()
0|PTMagic( |    at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonObjectFromURL(String url, LogHelper log, Boolean onlyLogDebug) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 45
0|PTMagic( | 2018-04-06 04:32 +00:00: 2018/04/06 04:32:46.990 INFO - Binance - Market data received for 301 currencies 
0|PTMagic( | 2018-04-06 04:32 +00:00: 2018/04/06 04:32:46.990 ERROR - Binance - Failed to get main market price for . 
0|PTMagic( | 2018/04/06 04:32:46.990 ERROR - Unable to contact Binance for fresh market data. Trying again in 1 minute(s). 

```

Problems are displayed in the PTMagic log for a few hours.

I am using the Binance BTC market trade.
It seems that the data can not be loaded.

This will also cause problems with versions 1.5.0 and earlier.

Please check.

**Comment by nicekon** [comment]
**settings.general.json** 
ProfitTrailerPath": "/volume1/ohnam/bot/pt1.2.6.25/binance/btc/"

Sorry. 
my mistake.

The PT file path was set incorrectly.
Resolved!
