### ISSUE TITLE
The remote server returned an error: (403) Forbidden. System.Net.WebException The remote server returned an error: (403) Forbidden.

### ISSUE THREAD

**Issue by tage202** [Legedric/ptmagic#426]
Just received this message an hr ago. Never had a problem until now. Can someone please let me know how to fix it?

2018/04/17 19:18:39.447 INFO - Starting market trend check with Version **1.5.2**
2018/04/17 19:18:40.550 FATAL - The remote server returned an error: (403) Forbidden. System.Net.WebException The remote server returned an error: (403) Forbidden.    at System.Net.HttpWebRequest.GetResponse()
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonObjectFromURL(String url, LogHelper log, Boolean onlyLogDebug) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 48
2018/04/17 19:18:40.639 FATAL - The remote server returned an error: (403) Forbidden. System.Net.WebException The remote server returned an error: (403) Forbidden.    at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonObjectFromURL(String url, LogHelper log, Boolean onlyLogDebug) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 59
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetLatestGitHubRelease(LogHelper log, String defaultVersion) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 132

Unhandled Exception: System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetLatestGitHubRelease(LogHelper log, String defaultVersion) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 141
   at PTMagic.PTMagic.MarketTrendCheckTimer_Elapsed(Object sender, ElapsedEventArgs e) in D:\Tools\PTMagic\PTMagic\PTMagic.cs:line 300
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 155

C:\Users\Administrator\Downloads\PTMagic.1.1.1>pause
Press any key to continue . . .

**Comment by tage202** [comment]
NVM. Fix it by recopying files back to Magic folder.
