### ISSUE TITLE
Error on starting PTMagic...

### ISSUE THREAD

**Issue by Crypto-Bites** [Legedric/ptmagic#43]
Hi,

I am running this program on my computer but I am getting this error message whenever I try to start it up. I don't why it is saying anything about a D drive.

------------------------------------------------------------------------------

2018/02/19 12:35:16.008 FATAL - Error loading configuration! System.FormatException Could not parse the JSON file. Error on line number '6': '"TestMode": true, // If TestMode is active, no properties files will be changes
"ProfitTrailerPath": "C:\\Users\Dave\Desktop\MainProfitTrailer\\", // Path to your Profit Trailer main directory (use double backslashes for windows like C:\\ProfitTrailer\\)'.    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Globals.SystemConfiguration.LoadSettings(String basePath) in D:\Tools\PTMagic\Globals\SystemConfiguration.cs:line 24
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 41

Unhandled Exception: System.FormatException: Could not parse the JSON file. Error on line number '6': '"TestMode": true, // If TestMode is active, no properties files will be changes
"ProfitTrailerPath": "C:\\Users\Dave\Desktop\MainProfitTrailer\\", // Path to your Profit Trailer main directory (use double backslashes for windows like C:\\ProfitTrailer\\)'. ---> Newtonsoft.Json.JsonReaderException: Bad JSON escape sequence: \D. Path 'GeneralSettings.Application.ProfitTrailerPath', line 6, position 39.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   --- End of inner exception stack trace ---
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 59

-------------------------------------------------------------

**Comment by TwixRaider** [comment]
Please use double backslashes in your Profit Trailer path instead of single backslashes: C:\Users\Dave\Desktop\MainProfitTrailer\

**Comment by Crypto-Bites** [comment]
I fixed it and I am still getting the same issue.

**Comment by Legedric** [comment]
Please post a screen of the error you are getting after you changed the path.

**Comment by sitespagando** [comment]
just put \\ and not just \ at the time of copying the address, I also did this stupid and in the installation is telling to do this and we do not pay attention.

**Comment by Crypto-Bites** [comment]
![capture](https://user-images.githubusercontent.com/36629846/36388633-18e47850-1577-11e8-9d8c-50ecc9782837.PNG)

**Comment by TwixRaider** [comment]
Please change EVERY \ to \\\ , not just the one at the end.

**Comment by Crypto-Bites** [comment]
That worked. I that info would be a great addition to the setting process. Thanks for that help.

**Comment by TwixRaider** [comment]
Your are right. I will add it to the setup guide and the troubleshooting section.
