### ISSUE TITLE
I use PT 2.0 with PTM 1.6.1 having this issue.

### ISSUE THREAD

**Issue by jojobobgg** [Legedric/ptmagic#452]
![wx20180424-181710](https://user-images.githubusercontent.com/38686781/39181338-eab6c31e-47eb-11e8-9fd5-27e2a98655de.png)
seems like can not connect to my remote pc, but I use pt 1.x that is ok, nothing problems.

**Comment by Legedric** [comment]
Please navigate to http://YourPTMMonitorURL/DashboardTop and see what error comes up there.

**Comment by jojobobgg** [comment]
it is showing blank page , nothing ...
![wx20180425-080430](https://user-images.githubusercontent.com/38686781/39219793-53e8c8c8-485f-11e8-9201-8661a17f4f76.png)

**Comment by stevenshizzleh** [comment]
Same here: 

Ticker update failed!

PTMagic Monitor failed to update data. If this error does not go away by itself, please check the connection to your hosting PC."

Nothing show in DashboardTop

**Comment by Legedric** [comment]
Sorry my bad, the correct URL would be:
http://YourPTMMonitorURL/_get/DashboardTop

or

http://YourPTMMonitorURL/_get/TickerWidget

**Comment by jojobobgg** [comment]
(http://yourptmmonitorurl/_get/DashboardTop) for this link, it is showing this error
Error.

An error occurred while processing your request.

Request ID: 0HLD9QLMME3UK:00000001

Could not find file 'C:\Users\Administrator\Desktop\ProfitTrailer2.0\ProfitTrailerData.json'.

at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
 at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
 at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
 at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
 at System.IO.File.InternalReadAllText(String path, Encoding encoding)
 at System.IO.File.ReadAllText(String path)
 at Globals.ProfitTrailerData..ctor(String ptmBasePath, SystemConfiguration systemConfiguration) in D:\Tools\PTMagic\Globals\ProfitTrailerData.cs:line 24
 at Monitor.Pages.DashboardTopModel.OnGet() in D:\Tools\PTMagic\Monitor\Pages\_get\DashboardTop.cshtml.cs:line 17
 at Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory.VoidHandlerMethod.Execute(Object receiver, Object[] arguments)
 at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.<InvokeHandlerMethodAsync>d__29.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.<InvokeNextPageFilterAsync>d__31.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
 at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
 at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.<InvokeInnerFilterAsync>d__22.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
 at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
 at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()

------------------------------------------
for  http://yourptmmonitorurl/_get/TickerWidget ,that is Blank page.

**Comment by jojobobgg** [comment]
issue resolved~thanks !
