### ISSUE TITLE
 Could not find file 'C:\Users\Administrator\Downloads\PTMagic.1.6.0\PTMagic 1.6.0\PTMagic\nlog.config'.

### ISSUE THREAD

**Issue by tage202** [Legedric/ptmagic#453]
Can't run PTMagic 1.6.0. I get this error message.

C:\Users\Administrator\Downloads\PTMagic.1.6.0\PTMagic 1.6.0\PTMagic>dotnet PTMagic.dll

Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'C:\Users\Administrator\Downloads\PTMagic.1.6.0\PTMagic 1.6.0\PTMagic\nlog.config'.
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at NLog.Config.XmlLoggingConfiguration..ctor(String fileName, Boolean ignoreErrors, LogFactory logFactory)
   at NLog.Extensions.Logging.ConfigureExtensions.ConfigureNLog(ILoggerFactory loggerFactory, String configFileRelativePath)
   at Globals.ServiceHelper.BuildLoggerService(String basePath) in D:\Tools\PTMagic\Globals\ServiceHelper.cs:line 27
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 17

C:\Users\Administrator\Downloads\PTMagic.1.6.0\PTMagic 1.6.0\PTMagic>pause
Press any key to continue . . .

**Comment by tage202** [comment]
My mistake. Forgot to copy the nlog.config file over.
