### ISSUE TITLE
PT Magic Monitor Loading Issues

### ISSUE THREAD

**Issue by Skelter0703** [Legedric/ptmagic#462]
I upgraded to 1.6.1 and started the monitor after the the magic was started, and the monitor didn't automatically open a google chrome window for local host 5000. I manually opened a tab and went to the site myself, and when i did the monitor was showing red error messages. The error messages was Ticker failure and Dashboard TOP failure? I made sure all my directory paths are correct in the app settings file and issue is still there. Please give some advice on how to fix this if anyone has experienced this before!!

**Comment by Legedric** [comment]
Please go to the url http://YourPTMMonitorUrl/_get/DashboardTop and post here what error comes up.

**Comment by Skelter0703** [comment]
i clicked on the link and says site not found

**Comment by Skelter0703** [comment]
This site can’t be reached
yourptmmonitorurl’s server IP address could not be found.
Search Google for your pet monitor url get Dashboard Top
ERR_NAME_NOT_RESOLVED

**Comment by Skelter0703** [comment]
www.profit-trailer-magic.com | GitHub | Wiki
Ticker update failed!
PTMagic Monitor failed to update data. If this error does not go away by itself, please check the connection to your hosting PC.
Dashboard (Top) update failed!
PTMagic Monitor failed to update data. If this error does not go away by itself, please check the connection to your hosting PC.

**Comment by Skelter0703** [comment]
Thats the red error messages i receive when i start the localhost 5000 manually

**Comment by Legedric** [comment]
@Skelter0703 Did you replace the YourPTMMonitorUrl part of the URL with your actual PTM monitor URL?
Like http://localhost:5000/_get/DashboardTop ?

**Comment by Skelter0703** [comment]
i dont know what URL you're talking about? i only changed the directory path in he monitor app file

**Comment by Legedric** [comment]
I meant this:
> Please go to the url http://YourPTMMonitorUrl/_get/DashboardTop and post here what error comes up.

When saying this:
> Did you replace the YourPTMMonitorUrl part of the URL with your actual PTM monitor URL?
> Like http://localhost:5000/_get/DashboardTop ?

As you said "I clicked the link" I assume you did not so the URL is of course invalid.

**Comment by Skelter0703** [comment]
no i didnt replace or change anything when it comes to the url to the monitor! When i would run the monitor on the old version of PTM i would automatically open the browser window for me, and now the new version is not doing that. So I open a browser tab and type localhost:5000 and that takes me to the monitor, however thats when the Ticker and Dashboard TOP errors start generating

**Comment by Skelter0703** [comment]
i have never had to type anything but localhost:5000, should i try to add that stuff at the end?

**Comment by VolatileCryptoJerk** [comment]
Make sure that you have the proper path to your Profit Trailer in settings.general.json

**Comment by Legedric** [comment]
@Skelter0703 Sorry dude but you are not getting what I want from you.

To see what error causes this I need you to go to:
http://localhost:5000/_get/DashboardTop

REPLACE localhost and the port in case you setup your PTM differently.

**Comment by Skelter0703** [comment]
and what file do I put that path in?

**Comment by Skelter0703** [comment]
when i just put that in my browser this is the error message i get

Error.
An error occurred while processing your request.
Request ID: 0HLDC8F503FEG:00000001

Offset must be within plus or minus 14 hours.
 Parameter name: offset
at System.DateTimeOffset.ValidateOffset(TimeSpan offset)
 at System.DateTimeOffset..ctor(Int64 ticks, TimeSpan offset)
 at System.DateTimeOffset.ToOffset(TimeSpan offset)
 at Globals.ProfitTrailerData.BuildSellLogData(List`1 rawSellLogData, SystemConfiguration systemConfiguration) in D:\Tools\PTMagic\Globals\ProfitTrailerData.cs:line 121
 at Globals.ProfitTrailerData..ctor(String ptmBasePath, SystemConfiguration systemConfiguration) in D:\Tools\PTMagic\Globals\ProfitTrailerData.cs:line 24
 at Monitor.Pages.DashboardTopModel.OnGet() in D:\Tools\PTMagic\Monitor\Pages\_get\DashboardTop.cshtml.cs:line 17
 at Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory.VoidHandlerMethod.Execute(Object receiver, Object[] arguments)
 at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.<InvokeHandlerMethodAsync>d__29.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.<InvokeNextPageFilterAsync>d__31.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
 at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
 at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.<InvokeInnerFilterAsync>d__22.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
 at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
 at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
