### ISSUE TITLE
monitor does not load

### ISSUE THREAD

**Issue by Ridonia** [Legedric/ptmagic#466]
Just updated recently to PT 2 and also PTM to 1.61
PTM is working, but the Monitor throws back this strange error:
`2|PTM-Moni | Unhandled Exception: 2018-04-28 00:12 +02:00: System.InvalidOperationException: Cannot see if a key has been pressed when either application does not have a console or when console input has been redirected from a file. Try Console.In.Peek.
2|PTM-Moni |    at System.Console.get_KeyAvailable()
2|PTM-Moni |    at Monitor.Program.Main(String[] args) in D:\Tools\PTMagic\Monitor\Program.cs:line 64
2|PTM-Moni | 2018-04-28 00:21 +02:00: 
2|PTM-Moni | Unhandled Exception: 2018-04-28 00:21 +02:00: System.InvalidOperationException: Cannot see if a key has been pressed when either application does not have a console or when console input has been redirected from a file. Try Console.In.Peek.
2|PTM-Moni |    at System.Console.get_KeyAvailable()
2|PTM-Moni |    at Monitor.Program.Main(String[] args) in D:\Tools\PTMagic\Monitor\Program.cs:line 78
2|PTM-Moni | 2018-04-28 03:00 +02:00: 
2|PTM-Moni | 2018-04-28 03:00 +02:00: Unhandled Exception:2018-04-28 03:00 +02:00:  2018-04-28 03:00 +02:00: System.InvalidOperationException: Cannot see if a key has been pressed when either application does not have a console or when console input has been redirected from a file. Try Console.In.Peek.
2|PTM-Moni |    at System.Console.get_KeyAvailable()
2|PTM-Moni |    at Monitor.Program.Main(String[] args) in D:\Tools\PTMagic\Monitor\Program.cs:line 78
2|PTM-Moni | 2018-04-28 09:42 +02:00: 
2|PTM-Moni | 2018-04-28 09:42 +02:00: Unhandled Exception: 2018-04-28 09:42 +02:00: System.InvalidOperationException: Cannot see if a key has been pressed when either application does not have a console or when console input has been redirected from a file. Try Console.In.Peek.
2|PTM-Moni |    at System.Console.get_KeyAvailable()
2|PTM-Moni |    at Monitor.Program.Main(String[] args) in D:\Tools\PTMagic\Monitor\Program.cs:line 78
`
Any Idea?

**Comment by Ridonia** [comment]
Solved...
I had to copy the "wwwroot" directory from the Monitor directory to the main PTMagic directory
Strange...
