### ISSUE TITLE
FATAL - The remote server returned an error: (403) Forbidden (AGAIN)

### ISSUE THREAD

**Issue by UWillC** [Legedric/ptmagic#477]
I am running PTMagic v1.6.1 on Linux but get few errors and then after try to restart I get this messages...

2018/05/01 11:02:54.166 INFO -
2018/05/01 11:02:54.355 INFO -   ██████╗ ████████╗    ███╗   ███╗ █████╗  ██████╗ ██╗ ██████╗
2018/05/01 11:02:54.356 INFO -   ██╔══██╗╚══██╔══╝    ████╗ ████║██╔══██╗██╔════╝ ██║██╔════╝
2018/05/01 11:02:54.356 INFO -   ██████╔╝   ██║       ██╔████╔██║███████║██║  ███╗██║██║
2018/05/01 11:02:54.356 INFO -   ██╔═══╝    ██║       ██║╚██╔╝██║██╔══██║██║   ██║██║██║
2018/05/01 11:02:54.356 INFO -   ██║        ██║       ██║ ╚═╝ ██║██║  ██║╚██████╔╝██║╚██████╗
2018/05/01 11:02:54.356 INFO -   ╚═╝        ╚═╝       ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚═╝ ╚═════╝
2018/05/01 11:02:54.356 INFO -                          Version 1.6.1
2018/05/01 11:02:54.356 INFO -
2018/05/01 11:02:54.981 INFO - Configuration loaded. Found 4 Market Trends, 6 Global Settings and 3 Single Market Settings.
2018/05/01 11:02:54.987 INFO - Profit Trailer found
2018/05/01 11:02:54.987 INFO - Profit Trailer license found
2018/05/01 11:02:54.987 INFO - Profit Trailer default setting name specified
2018/05/01 11:02:54.987 INFO - Profit Trailer monitor URL found
2018/05/01 11:02:55.111 INFO - Profit Trailer monitor connection test succeeded
2018/05/01 11:02:55.138 INFO - Checking automated settings for presets...
2018/05/01 11:02:55.150 INFO - Prepared PAIRS.properties for 'Default'
2018/05/01 11:02:55.150 INFO - Prepared DCA.properties for 'Default'
2018/05/01 11:02:55.152 INFO - Prepared INDICATORS.properties for 'Default'
2018/05/01 11:02:55.152 INFO - Checking market trends every 5 minutes...
2018/05/01 11:02:55.344 INFO -
2018/05/01 11:02:55.344 INFO - ##########################################################
2018/05/01 11:02:55.344 INFO - #********************************************************#
2018/05/01 11:02:55.344 INFO - Starting market trend check with Version 1.6.1
2018/05/01 11:02:56.233 FATAL - The remote server returned an error: (403) Forbidden. System.Net.WebException The remote server returned an error: (403) Forbidden.    at System.Net.HttpWebRequest.GetResponse()
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonObjectFromURL(String url, LogHelper log, Boolean onlyLogDebug) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 48
2018/05/01 11:02:56.308 FATAL - The remote server returned an error: (403) Forbidden. System.Net.WebException The remote server returned an error: (403) Forbidden.    at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonObjectFromURL(String url, LogHelper log, Boolean onlyLogDebug) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 59
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetLatestGitHubRelease(LogHelper log, String defaultVersion) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 132

Unhandled Exception: System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetLatestGitHubRelease(LogHelper log, String defaultVersion) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 141
   at PTMagic.PTMagic.MarketTrendCheckTimer_Elapsed(Object sender, ElapsedEventArgs e) in D:\Tools\PTMagic\PTMagic\PTMagic.cs:line 320
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 192
Aborted (core dumped)

I checked github issues but found that PTMagic should run but I had failure in running it.

**Comment by UWillC** [comment]
I do not know what is causing the issue, but now this was resolved somehow ??
