### ISSUE TITLE
random ASP error

### ISSUE THREAD

**Issue by JeromeF91** [Legedric/ptmagic#480]
sometime i got this kind of errors : 

Error.
An error occurred while processing your request.
Request ID: 0HLDEQL9TI3OR:00000001

Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index
at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException() at Globals.SystemHelper.IsRecentVersion(String currentVersion, String latestVersion) in D:\Tools\PTMagic\Globals\SystemHelper.cs:line 925 at CallSite.Target(Closure , CallSite , Type , Object , Object ) at Monitor.Pages._Layout_View.<<ExecuteAsync>b__8_1>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.<SetOutputContentAsync>d__30.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Monitor.Pages._Layout_View.<ExecuteAsync>d__8.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageCoreAsync>d__16.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__15.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderLayoutAsync>d__18.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context) at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context) at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()

Tried to restart both monitor and backend, same issue. If i wait to the issue disapear after some time.

Thanks for your great work ! :)

Jerome

**Comment by JeromeF91** [comment]
and this is the output of the console while i'm facing the issue : 

1|PTm3-bin | 2018-05-01 12:28 -04:00: 2018/05/01 12:28:23.712 WARN - PTMagic already raiding since 05/01/2018 12:23:23 - Process frozen? Checking things...
1|PTm3-bin | 2018-05-01 12:33 -04:00: 2018/05/01 12:33:23.711 WARN - PTMagic already raiding since 05/01/2018 12:23:23 - Process frozen? Checking things...
1|PTm3-bin | 2018-05-01 12:33 -04:00: 2018/05/01 12:33:23.711 WARN - PTMagic seems to have frozen after raid 224, but don't worry I will sacrifice some Magicbots to get this running again...
1|PTm3-bin | 2018/05/01 12:33:23.711 INFO - PTMagic status resetted, waiting for the next raid to be good to go again.
1|PTm3-bin | 2018-05-01 12:38 -04:00: 2018/05/01 12:38:23.712 INFO -
1|PTm3-bin | 2018-05-01 12:38 -04:00: 2018/05/01 12:38:23.712 INFO - ##########################################################
1|PTm3-bin | 2018/05/01 12:38:23.712 INFO - #********************************************************#
1|PTm3-bin | 2018/05/01 12:38:23.712 INFO - Starting market trend check with Version 1.6.1
1|PTm3-bin | 2018-05-01 12:38 -04:00: 2018/05/01 12:38:24.095 FATAL - The remote server returned an error: (403) Forbidden. System.Net.WebException The remote server returned an error: (403) Forbidden.    at System.Net.HttpWebRequest.GetResponse()
1|PTm3-bin |    at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonObjectFromURL(String url, LogHelper log, Boolean onlyLogDebug) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 48
1|PTm3-bin | 2018-05-01 12:38 -04:00: 2018/05/01 12:38:24.097 FATAL - The remote server returned an error: (403) Forbidden. System.Net.WebException The remote server returned an error: (403) Forbidden.    at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonObjectFromURL(String url, LogHelper log, Boolean onlyLogDebug) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 59
1|PTm3-bin |    at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetLatestGitHubRelease(LogHelper log, String defaultVersion) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 132
1|PTm3-bin | 2018-05-01 12:43 -04:00: 2018/05/01 12:43:23.711 WARN - PTMagic already raiding since 05/01/2018 12:38:23 - Process frozen? Checking things...
1|PTm3-bin | 2018-05-01 12:43 -04:00: 2018/05/01 12:43:23.711 WARN - PTMagic seems to have frozen after raid 225, but don't worry I will sacrifice some Magicbots to get this running again...
1|PTm3-bin | 2018/05/01 12:43:23.711 INFO - PTMagic status resetted, waiting for the next raid to be good to go again.

It happens on both Binance and Bittrex and at the same time.
