### ISSUE TITLE
PTMagic not able to load settings?

### ISSUE THREAD

**Issue by radawson** [Legedric/ptmagic#483]
I'm getting this error in my console:

`
2018/05/02 00:48:21.018 INFO - Loading current Profit Trailer properties from API...
2018/05/02 00:50:30.770 FATAL - Loading PAIRS.properties failed for setting 'Default': The operation was canceled. System.OperationCanceledException The operation was canceled.    at System.Net.HttpWebRequest.GetResponse()
   at BusinessRules.PTSettings.SettingsHandler.GetPropertyLinesFromAPI(String ptFileName, SystemConfiguration systemConfiguration, LogHelper log) in D:\Tools\PTMagic\BusinessRules\PTSettings\SettingsHandler.cs:line 49
2018/05/02 00:52:43.875 FATAL - Loading DCA.properties failed for setting 'Default': The operation was canceled. System.OperationCanceledException The operation was canceled.    at System.Net.HttpWebRequest.GetResponse()
   at BusinessRules.PTSettings.SettingsHandler.GetPropertyLinesFromAPI(String ptFileName, SystemConfiguration systemConfiguration, LogHelper log) in D:\Tools\PTMagic\BusinessRules\PTSettings\SettingsHandler.cs:line 49
2018/05/02 00:52:44.351 ERROR - Unable to load all Profit Trailer properties!
`
The settings name seems to be correct in settings.general.json. Is there somewhere else I should be looking?

**Comment by Legedric** [comment]
Make sure your Profit Trailer monitor is running and you do not block access to it in any kind from the same machine.
