### ISSUE TITLE
Mac install

### ISSUE THREAD

**Issue by ddey94** [Legedric/ptmagic#501]
followed all steps. got this error when running dotnet PTMagic.dll

`Unhandled Exception: System.PlatformNotSupportedException: The handler does not support custom handling of certificates with this combination of libcurl (7.54.0) and its SSL backend ("LibreSSL/2.0.20").
   at System.Net.HttpWebRequest.GetResponse()
   at Globals.SystemHelper.UrlIsReachable(String url) in D:\Tools\PTMagic\Globals\SystemHelper.cs:line 810
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 168
Abort trap: 6`

**Comment by Legedric** [comment]
Duplicate of #450
