### ISSUE TITLE
Monitor Ptmagic

### ISSUE THREAD

**Issue by duythien** [Legedric/ptmagic#560]
Hello

I have following your step and setup success Ptmagic

```
2018/06/22 11:10:59.749 INFO - Building single market settings 'PumpNDumpProtection' for 'BTC-NBT'... 
2018/06/22 11:10:59.749 INFO - Built single market settings 'PumpNDumpProtection' for 'BTC-NBT'. 
2018/06/22 11:10:59.749 INFO - Building single market settings 'FreefallBlock' for 'BTC-NGC'... 
2018/06/22 11:10:59.749 INFO - Built single market settings 'FreefallBlock' for 'BTC-NGC'. 
2018/06/22 11:10:59.749 INFO - Building single market settings 'BlacklistNewCoins' for 'BTC-NLC2'... 
2018/06/22 11:10:59.749 INFO - Built single market settings 'BlacklistNewCoins' for 'BTC-NLC2'. 
2018/06/22 11:10:59.749 INFO - Building single market settings 'PumpNDumpProtection' for 'BTC-RVR'... 
2018/06/22 11:10:59.749 INFO - Built single market settings 'PumpNDumpProtection' for 'BTC-RVR'. 
2018/06/22 11:10:59.749 INFO - Building single market settings 'PumpNDumpProtection' for 'BTC-SPHR'... 
2018/06/22 11:10:59.749 INFO - Built single market settings 'PumpNDumpProtection' for 'BTC-SPHR'. 
2018/06/22 11:10:59.749 INFO - Building single market settings 'PumpNDumpProtection' for 'BTC-THC'... 
2018/06/22 11:10:59.749 INFO - Built single market settings 'PumpNDumpProtection' for 'BTC-THC'. 
2018/06/22 11:10:59.749 INFO - Building single market settings 'PumpNDumpProtection' for 'BTC-TX'... 
2018/06/22 11:10:59.749 INFO - Built single market settings 'PumpNDumpProtection' for 'BTC-TX'. 
2018/06/22 11:10:59.749 INFO - Building single market settings 'PumpNDumpProtection' for 'BTC-XST'... 
2018/06/22 11:10:59.749 INFO - Built single market settings 'PumpNDumpProtection' for 'BTC-XST'. 
2018/06/22 11:10:59.749 INFO - Building single market settings completed. 
2018/06/22 11:10:59.756 INFO - Saving properties using API... 
2018/06/22 11:10:59.756 INFO - All properties saved! 
2018/06/22 11:10:59.786 INFO - Single Market Settings Summary saved. 
2018/06/22 11:10:59.817 INFO - Building LastRuntimeSummary.json for your monitor... 
2018/06/22 11:10:59.817 INFO - Summary: Building global settings summary... 
2018/06/22 11:10:59.817 INFO - Summary: Built global settings summary. 
2018/06/22 11:10:59.817 INFO - Summary: Save market trend changes for summary. 
2018/06/22 11:10:59.817 INFO - Summary: Market trends saved. 
2018/06/22 11:10:59.817 INFO - Summary: Getting current global properties... 
2018/06/22 11:10:59.847 INFO - Summary: Current global properties saved. 
2018/06/22 11:10:59.847 INFO - Summary: Getting current single market properties... 
2018/06/22 11:10:59.849 INFO - Summary: Current single market properties saved. 
2018/06/22 11:10:59.891 INFO - Summary: LastRuntimeSummary.json saved. 
2018/06/22 11:10:59.891 INFO - Cleaned up logfiles. 
2018/06/22 11:10:59.891 INFO - ########################################################## 
2018/06/22 11:10:59.891 INFO - #******************* RAID SUMMARY ********************# 
2018/06/22 11:10:59.891 INFO - + PT Magic Version: 2.0.1 
2018/06/22 11:10:59.891 WARN - + Your version is out of date! The most recent version is 2.0.3 
2018/06/22 11:10:59.893 INFO - + Proft Trailer Major Version: 2 
2018/06/22 11:10:59.893 INFO - + Instance name: PT Magic 
2018/06/22 11:10:59.893 INFO - + Time spent: 5m 59s 
2018/06/22 11:10:59.893 INFO - + Active setting: Default 
2018/06/22 11:10:59.893 INFO - + Global setting changed: No  
2018/06/22 11:10:59.893 INFO - + Files changed: No 
2018/06/22 11:10:59.893 INFO - + Markets with active single market settings: 13 
2018/06/22 11:10:59.893 INFO - +   BlacklistNewCoins: 3 
2018/06/22 11:10:59.893 INFO - +   PumpNDumpProtection: 9 
2018/06/22 11:10:59.893 INFO - +   FreefallBlock: 1 
2018/06/22 11:10:59.893 INFO - + 359 Magicbots killed in 1 raids on Cryptodragon's Lair 5. 
2018/06/22 11:10:59.893 INFO -  
2018/06/22 11:10:59.893 INFO - DO NOT CLOSE THIS WINDOW! THIS IS THE BOT THAT ANALYZES TRENDS AND CHANGES SETTINGS! 
2018/06/22 11:10:59.893 INFO -  
2018/06/22 11:10:59.893 INFO - #********************************************************# 
2018/06/22 11:10:59.893 INFO - ########################################################## 

```

But when i try to running monitor it seem that do not work, the error below

```
root@b24b709664c9:/app# dotnet ./Monitor/Monitor.dll
##########################################################
#********************************************************#
INFO: Starting PT Magic Monitor...
INFO: Beginning startup checks...
INFO: appsettings.json found in /app/Monitor

Unhandled Exception: System.FormatException: Could not parse the JSON file. Error on line number '0': '﻿{'. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: ﻿. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Monitor.Program.Main(String[] args) in D:\Tools\ptmagic-github\Monitor\Program.cs:line 34
Aborted (core dumped)
```

The appsetting.json file below

```
{
  "PTMagicBasePath": "/app/", // Path to your Profit Trailer Magic main directory (use double backslashes for windows like C:\\PTMagic\\)
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Warning"
    }
  }
}
```

**Comment by Legedric** [comment]
Please make sure there is no hidden character in front of your first opening curly bracket.

It seems like there is something like a linebreak or something else in front of that in your appsettings.json file that invalidates your json.

**Comment by duythien** [comment]
@Legedric It work now. Thanks
