### ISSUE TITLE
PTMagic - unable to load ProfitTrailerData.json (because was not created)

### ISSUE THREAD

**Issue by F1shst4le** [Legedric/ptmagic#582]
Hello, i just installed PTMagic and it runs, 
but the Monitor does not load (except sites like Settings,General, ... )

I am using Windows 10
ProfitTrailer 2.19
PTMagic 2.04

What can i do?
this is my error:
Error.
An error occurred while processing your request.
Request ID: 0HLGFARIFML1M:0000002B

Unable to load Profit Trailer data file at: R:\data\Dropbox\_dev\Trading\Tradingbot\ProfitTrailer\PTMagicBinance\ProfitTrailerData.json
at Core.Main.DataObjects.ProfitTrailerData..ctor(String ptmBasePath, PTMagicConfiguration systemConfiguration) in D:\Data\Github\djb-ptmagic\Core\DataObjects\ProfitTrailerData.cs:line 14
 at lambda_method(Closure , Object , Object[] )
 at Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory.VoidHandlerMethod.Execute(Object receiver, Object[] arguments)
 at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeHandlerMethodAsync()
 at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeNextPageFilterAsync()
 at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
 at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
 at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeInnerFilterAsync()
 at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
 at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
 at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
 at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
 at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
 at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
 at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
 at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
 at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)

**Comment by NobleVision** [comment]
The new versions of Profit Trailer (v2.1.16+) puts the 'ProfitTrailerData.json' file in the 'data' directory under the install directory and Profit Trailer Magic is looking for it in the Profit Trailer install directory.
