### ISSUE TITLE
MAC OSX - dotnet-sdk-2.1.4

### ISSUE THREAD

**Issue by duplexdigital** [Legedric/ptmagic#91]
Is there an alternative to .NET for mac?     The newest software update is not compatible with my OS; El Capitan.   Also, the previous version (dotnet-sdk-2.0.0-preview2-006497-osx-x64) does not install/ open correctly.   Not sure if Visual Studio for Mac would be the solution.    Any help would be appreciated!

**Comment by cyberience** [comment]
I am also not able to run this on a mac.
Details as follows:
2018/02/21 20:18:46.209 FATAL - Error loading configuration! System.IO.FileNotFoundException The configuration file 'settings.general.json' was not found and is not optional. The physical path is '/Users/geoffrey/_dev/PTMagic/settings.general.json'.    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Globals.SystemConfiguration.LoadSettings(String basePath) in D:\Tools\PTMagic\Globals\SystemConfiguration.cs:line 24
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 41

**Comment by Legedric** [comment]
@cyberience Have you checked if the file is located where the error messages expects it to be?

**Comment by jbgwong** [comment]
I have a similar error message, is there somewhere defines the Path, Mac do not have D drive . 
Error:
Unhandled Exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Average[TSource](IEnumerable`1 source, Func`2 selector)
   at PTMagic.PTMagic.MarketTrendCheckTimer_Elapsed(Object sender, ElapsedEventArgs e) in D:\Tools\PTMagic\PTMagic\PTMagic.cs:line 393
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 177

**Comment by Legedric** [comment]
@jbgwong 
The d:\ message is irrelevant, the error is not Mac related, this is a known and tricky issue that I am chasing.
For the moment, please try this:
- Stop PT Magic (the one bot that has these errors)
- Delete the folder named "Exchange" inside "_data" in PT Magic
- Start the bot again (it will take up to 15 minutes again to rebuild the exchange data)
